name: flutter_boilerplate
description: "A robust, scalable Clean Architecture Flutter boilerplate with BLoC, AutoRoute, Injectable, and Dio."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  auto_route: ^11.1.0
  get_it: ^9.2.1
  injectable: ^2.5.0
  dio: ^5.11.0
  dartz: ^0.10.1
  flutter_secure_storage: ^10.3.1
  intl: ^0.20.2
  marionette_flutter: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  auto_route_generator: ^10.5.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
